# Generated by Django 4.2.7 on 2025-10-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff_department_new_alter_staff_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AddField(
            model_name='staff',
            name='enterprise_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='企业邮箱'),
        ),
        migrations.AddField(
            model_name='staff',
            name='enterprise_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='企业手机号'),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='办公电话'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='role_type',
            field=models.CharField(choices=[('enterprise_admin', '企业管理员'), ('department_manager', '部门经理'), ('team_leader', '团队负责人'), ('regular_staff', '普通员工'), ('contractor', '合同工')], default='regular_staff', max_length=20, verbose_name='角色类型'),
        ),
    ]
