# Generated by Django 4.2.7 on 2025-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_avatar_remove_staff_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('employed', '在职'), ('resigned', '离职')], default='employed', max_length=20, verbose_name='就业状态'),
        ),
    ]
