# Generated by Django 4.2.7 on 2025-09-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='企业名称')),
                ('unified_social_credit_code', models.CharField(max_length=18, unique=True, verbose_name='统一社会信用代码')),
                ('legal_representative', models.CharField(max_length=100, verbose_name='法定代表人')),
                ('registered_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='注册资本')),
                ('establishment_date', models.DateField(verbose_name='成立日期')),
                ('business_term_start', models.DateField(verbose_name='营业期限开始')),
                ('business_term_end', models.DateField(blank=True, null=True, verbose_name='营业期限结束')),
                ('business_scope', models.TextField(verbose_name='经营范围')),
                ('registration_authority', models.CharField(max_length=200, verbose_name='登记机关')),
                ('registered_address', models.TextField(verbose_name='注册地址')),
                ('contact_address', models.TextField(verbose_name='联系地址')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('max_users', models.IntegerField(default=10, verbose_name='最大用户数')),
                ('subscription_tier', models.CharField(default='basic', max_length=50, verbose_name='订阅等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业管理',
                'db_table': 'enterprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(max_length=50, verbose_name='应用代码')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('suspended', '暂停'), ('expired', '过期')], default='inactive', max_length=20, verbose_name='状态')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '企业订阅',
                'verbose_name_plural': '企业订阅管理',
                'db_table': 'enterprise_subscriptions',
                'unique_together': {('enterprise', 'app_code')},
            },
        ),
    ]
