# Generated by Django 4.2.7 on 2025-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='business_scope',
            field=models.TextField(blank=True, null=True, verbose_name='经营范围'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='business_term_start',
            field=models.DateField(blank=True, null=True, verbose_name='营业期限开始'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='成立日期'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='registered_address',
            field=models.TextField(blank=True, null=True, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='registered_capital',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='注册资本'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='registration_authority',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='登记机关'),
        ),
    ]
