# Generated by Django 5.2.6 on 2025-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_alter_enterprise_business_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='法定代表人'),
        ),
    ]
