# Generated by Django 4.2.7 on 2025-09-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_alter_enterprise_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.CharField(blank=True, choices=[('limited_liability_company_natural', '有限责任公司（自然人投资或控股）'), ('limited_liability_company_state', '有限责任公司（国有独资）'), ('joint_stock_limited_company', '股份有限公司'), ('social_group', '社会团体法人'), ('private_non_enterprise', '民办非企业单位'), ('individual_enterprise', '个体工商户'), ('other', '其他')], max_length=100, null=True, verbose_name='企业类型'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='enterprise_logos/', verbose_name='企业LOGO'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='企业网站'),
        ),
    ]
