# Generated by Django 4.2.7 on 2025-10-03 15:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0004_enterprise_enterprise_type_enterprise_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='部门的中文名称，不能包含特殊字符', max_length=100, validators=[django.core.validators.RegexValidator(message='部门名称不能包含特殊字符', regex='^[^!@#$%^&*(),.?":{}|<>]+$')], verbose_name='部门名称')),
                ('code', models.CharField(blank=True, help_text='企业内部的部门编码，可选', max_length=50, null=True, verbose_name='部门编码')),
                ('description', models.TextField(blank=True, help_text='部门的职责、权限等描述信息', null=True, verbose_name='部门描述')),
                ('is_active', models.BooleanField(default=True, help_text='停用后，部门将不会在列表中显示', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='enterprises.enterprise', verbose_name='所属企业')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='enterprises.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门管理',
                'db_table': 'departments',
                'ordering': ['name'],
                'unique_together': {('name', 'enterprise', 'parent')},
            },
        ),
    ]
