# Generated by Django 4.2.7 on 2025-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信UnionID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('enterprise_admin', '企业管理员'), ('enterprise_user', '企业用户'), ('independent_user', '独立用户')], default='enterprise_user', max_length=20, verbose_name='用户类型'),
        ),
    ]
