# Generated by Django 4.2.7 on 2025-10-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_department'),
        ('accounts', '0002_user_wechat_openid_user_wechat_unionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='enterprises.department', verbose_name='所属部门'),
        ),
    ]
