# Generated by Django 4.2.7 on 2025-10-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_avatar_remove_user_bio_and_more'),
    ]

    operations = [
    ]
