# Generated by Django 4.2.7 on 2025-09-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('location', models.CharField(max_length=200, verbose_name='认定地点')),
                ('examiner', models.CharField(max_length=100, verbose_name='主考人')),
                ('max_participants', models.IntegerField(default=50, verbose_name='最大参与人数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '认定计划',
                'verbose_name_plural': '认定计划管理',
                'db_table': 'assessment_plans',
            },
        ),
        migrations.CreateModel(
            name='SkillStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('code', models.CharField(max_length=50, verbose_name='技能代码')),
                ('description', models.TextField(blank=True, verbose_name='技能描述')),
                ('level', models.CharField(max_length=50, verbose_name='等级')),
                ('requirements', models.TextField(verbose_name='认定要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '技能标准',
                'verbose_name_plural': '技能标准管理',
                'db_table': 'skill_standards',
                'unique_together': {('enterprise', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100, verbose_name='参与者姓名')),
                ('participant_id', models.CharField(max_length=18, verbose_name='身份证号')),
                ('participant_department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('assessment_date', models.DateField(auto_now_add=True, verbose_name='认定日期')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('result', models.CharField(choices=[('passed', '通过'), ('failed', '未通过'), ('absent', '缺考')], max_length=20, verbose_name='认定结果')),
                ('comments', models.TextField(blank=True, verbose_name='评语')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='证书编号')),
                ('assessment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessment.assessmentplan', verbose_name='认定计划')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '认定记录',
                'verbose_name_plural': '认定记录管理',
                'db_table': 'assessment_records',
            },
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='skill_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_assessment.skillstandard', verbose_name='技能标准'),
        ),
    ]
