# Generated by Django 4.2.7 on 2025-09-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_alter_enterprise_business_scope_and_more'),
        ('skill_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统配置')),
            ],
            options={
                'verbose_name': '职业技能认定配置',
                'verbose_name_plural': '职业技能认定配置管理',
                'db_table': 'skill_assessment_config',
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentEnterpriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='认定业务联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='认定联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='认定联系邮箱')),
                ('org_type', models.CharField(blank=True, choices=[('management', '管理机构'), ('agent', '代理商'), ('assessment_site', '考核点'), ('evaluation_org', '职业技能等级评价机构')], max_length=20, verbose_name='机构类型')),
                ('evaluation_subtype', models.CharField(blank=True, choices=[('employer', '用人单位'), ('training_org', '社会培训评价组织'), ('technical_school', '技工院校')], max_length=20, verbose_name='评价机构子类型')),
                ('qualification_number', models.CharField(blank=True, max_length=100, verbose_name='资质编号')),
                ('qualification_date', models.DateField(blank=True, null=True, verbose_name='资质获得日期')),
                ('qualification_expiry', models.DateField(blank=True, null=True, verbose_name='资质有效期至')),
                ('business_scope', models.TextField(blank=True, verbose_name='认定业务范围')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='应用配置')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '职业技能认定企业档案',
                'verbose_name_plural': '职业技能认定企业档案管理',
                'db_table': 'skill_assessment_enterprise_profiles',
                'unique_together': {('enterprise',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='skillstandard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assessmentplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessmentplan',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='assessmentplan',
            name='location',
        ),
        migrations.RemoveField(
            model_name='assessmentplan',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='assessmentplan',
            name='status',
        ),
        migrations.DeleteModel(
            name='AssessmentRecord',
        ),
        migrations.RemoveField(
            model_name='skillstandard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skillstandard',
            name='requirements',
        ),
    ]
